sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HR4PHHb39mF4r73nqwOcZD+2wpVcTLvEMYCGmGMYhpgY3sru7Os+LwIpa1KhHrRYEarogJiRbUJbUiGaLgBXcVW05aAcMve2ShuLmYVHUg/eEPCNDxmVaYHXJKJ180OqKiq+g+4N7EvkFUNAoQjVkOqqE5oaKxj7Zb/F5OKnWRBkIa8H2LUiT0lktDRZS6ftJ0iZ/Fa1b6LNGFWe5ai/FmHYRIXx2LBNAaDCm7v8oL3qOIPa//BlH74S6w8yuXE0FDTU3xMp/6SWLAQvI9UW5EcdbIGIyXSJLKeY+e/x2snk+8ywDJMJlYE8aJRr4dNVBR+m1xoYpoXxtpwrCtRTdgkaPeFgXaAA6ZqUvAoWrnQkUgJqqxEhHY/Hh0yFDdS5c2sfdsg1VhT1g1fzGOlCsb1GarPf34DT17sWvoIpHHMuLqlzO47l7/PNp99/sJDVkZJNBt7Z9rKn4nP6ibCMlBGO3qyTC6uqYpF0SpIIejye+139M2WKx6ocg+ad+qLP3CAigGYWJfyL9lqM/nauONDyb1xaJ847sl3viZEufkLvrTeXQShRVV6Gmg3fPSzV2JHwBscTpKS+BiMMyrPFtCvtzXqm7QyJJ1cEpIXJJwa9Q0scFV8vIUVwKdYIBH9gNRBpR2oZaKxxoibX4LtLS3yJRNq/O6wyD/yEfHr1qK8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Works-of-Edgar-Allan-Poe---Volume-1_2147
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy